### ISSUE TITLE
Η ιστοσελίδα είναι ακόμα σε λειτουργεία;

### ISSUE THREAD

**Issue by thealonealex** [kostasx/greektext2speech#1]
Στο πρόγραμμα υπάρχει ένα url και όταν πήγα να το τρέξω μου έβγαλε error "no connection could be made because the target machine actively refused it"

**Comment by kostasx** [comment]
Καλησπέρα. Δεν ξέρω γιατί εμφανίζεται το συγκεκριμένο μήνυμα. Μόλις έκανα ένα γρήγορο test με το καινούργιο αρχείο που ανέβασα (acapela.python3.py, υποστηρίζει Python3) και το πρόγραμμα δουλεύει κανονικά.

Μήπως προσπάθησες να κάνεις πολλά request και σε μπλόκαρε η υπηρεσία;

Δες μήπως μπορείς να αλλάξεις την IP σου (π.χ. κάνοντας reset στον Router) και δοκίμασε ξανά.

**Comment by thealonealex** [comment]
Πολλά request δεν έκανα, αλλά χρησιμοποιούσα python 3. Θα το ξαναδοκιμάσω αργότερα με το καινούργιο αρχείο, ευχαριστώ.

**Comment by thealonealex** [comment]
Καλημέρα. Η έκδοση για python 3 λειτουργεί μια χαρά, ευχαριστώ πολύ!
